version: '3'
services:
  feed_fetcher:
    build:
      context: ./backend-golang
      dockerfile: Dockerfile
    networks:
      - curio-net
    volumes:
      - backend-golang-data:/app/data

  feed_parser:
    build:
      context: ./backend-rust
      dockerfile: Dockerfile
    networks:
      - curio-net
    volumes:
      - backend-rust-data:/app/data

  curio-router:
    build:
      context: ./nginx-router
      dockerfile: Dockerfile
    networks:
      curio-net:
        ipv4_address: 192.168.200.10

  feed_datastore:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      curio-net:
        ipv4_address: 192.168.200.90

networks:
  curio-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
