version: '3'
services:
  feed_fetcher:
    build:
      context: ./feed_fetcher
      dockerfile: Dockerfile
    volumes:
      - ./feed_fetcher:/usr/src/app
    environment:
      timezone: 'Asia/Tokyo'
    depends_on:
      feed_data:
        condition: service_healthy
    networks:
      curio-net:
        ipv4_address: 192.168.200.101

  feed_parser:
    build:
      context: ./feed_parser
      dockerfile: Dockerfile
    volumes:
      - ./feed_parser:/usr/src/app
    environment:
      timezone: 'Asia/Tokyo'
    depends_on:
      feed_data:
        condition: service_healthy
    networks:
      curio-net:
        ipv4_address: 192.168.200.201

  curio_router:
    build:
      context: ./curio_router
      dockerfile: Dockerfile
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./curio_router:/usr/share/nginx/html
      - ./curio_router/config/nginx.conf:/etc/nginx.conf
      - ./curio_router/nginx:/var/www/html
      - ./curio_router/app:/var/www/log
      - ./curio_router/nginx/logs:/var/log/nginx
    networks:
      curio-net:
        ipv4_address: 192.168.200.10

  feed_data:
    image: postgres
    volumes:
      - ./feed_data/data:/var/lib/postgresql/data
    environment:
      timezone: 'Asia/Tokyo'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 20s
      retries: 10
    restart: always
    networks:
      curio-net:
        ipv4_address: 192.168.200.90

networks:
  curio-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
