version: '3'
services:
  feed_fetcher:
    build:
      context: ./feed_fetcher
      dockerfile: Dockerfile
    volumes:
      - feed_fetcher:/usr/src/app
    networks:
      curio-net:
        ipv4_address: 192.168.200.101

  feed_parser:
    build:
      context: ./feed_parser
      dockerfile: Dockerfile
    volumes:
      - feed_parser:/usr/src/app
    networks:
      curio-net:
        ipv4_address: 192.168.200.201

  curio_router:
    build:
      context: ./curio_router
      dockerfile: Dockerfile
    volumes:
      - ./curio_router/nginx.conf:/etc/nginx/nginx.conf
    networks:
      curio-net:
        ipv4_address: 192.168.200.10

  feed_data:
    image: postgres
    volumes:
      - feed_data:/var/lib/postgresql/data
    networks:
      curio-net:
        ipv4_address: 192.168.200.90

networks:
  curio-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
