import Config


config :potionGather, PotionGather.Repo,
  username: "user1",
  password: "wanDOIHWfoiuhqF(#(Q)@fq828g2)",
  hostname: "192.168.200.90",
  database: "feed_data",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :potionGather, PotionGatherWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: PotionGather.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
